#!/bin/bash
#SBATCH --job-name=MoS2
#SBATCH -o out_%j.log
#SBATCH -e err_%j.log
#SBATCH --qos=hennig-b
#SBATCH --ntasks=16
#SBATCH --mem-per-cpu=800mb

#SBATCH -t 6:00:00
cd $SLURM_SUBMIT_DIR

module load intel/2016.0.109
module load openmpi/1.10.1
module load vasp/5.4.1

mpirun /home/mashton/vasp.5.4.1/bin/vasp_noz > job.log

echo 'Done.'
