#!/bin/sh
#PBS -N SiP
#PBS -o test.out
#PBS -e test.err
#PBS -r n
#PBS -l walltime=6:00:00
#PBS -l nodes=1:ppn=8
#PBS -l pmem=600mb
#PBS -W group_list=hennig

cd $PBS_O_WORKDIR

mpirun ~/bin/vasp_noz > job.log

echo 'Done.'
